--
create table if not exists categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            not null,
    CONSTRAINT pk_categories primary key (id)
);

create table if not exists compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned boolean                                 not null,
    title  varchar(255)                            not null,
    constraint pk_compilations primary key (id)
);

create table if not exists locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat double precision                        not null,
    lon double precision                        not null,
    constraint pk_locations primary key (id)
);

create table if not exists users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email varchar(320)                            not null,
    name  varchar(255)                            not null,
    constraint pk_users primary key (id)
);

create table if not exists events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         varchar(255),
    title              varchar(255),
    views              BIGINT,
    confirmed_requests bigint,
    event_date         TIMESTAMP without time zone             not null,
    paid               boolean,
    category_id        bigint                                  not null,
    initiator_id       bigint                                  not null,
    location_id        bigint                                  not null,
    created_on         timestamp without time zone             not null,
    description        varchar(2044)                           not null,
    participant_limit  int,
    published_on       timestamp without time zone             not null,
    request_moderation boolean,
    state              varchar(255),
    constraint pk_events primary key (id),
    constraint fk_events_categories foreign key (category_id) references categories (id) on delete cascade,
    constraint fk_events_users foreign key (initiator_id) references users (id) on delete cascade,
    constraint fk_events_locations foreign key (location_id) references locations (id) on delete cascade
);

create table if not exists compilations_events
(
    compilation_id bigint not null,
    event_id       bigint not null,
    constraint pk_compilations_events primary key (compilation_id, event_id),
    constraint fk_compilations_events_compilations foreign key (compilation_id) references compilations (id) on delete cascade,
    constraint fk_compilations_events_events foreign key (event_id) references events (id) on delete cascade
)