--
create table if not exists categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             not null unique,
    CONSTRAINT pk_categories primary key (id)
);

create table if not exists compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned boolean                                 not null,
    title  varchar(255)                            not null,
    constraint pk_compilations primary key (id)
);


create table if not exists users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email varchar(320)                            not null,
    name  varchar(255)                            not null,
    constraint pk_users primary key (id)
);

create table if not exists events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         varchar(2000),
    title              varchar(120),
    confirmed_requests bigint,
    event_date         TIMESTAMP without time zone             not null,
    paid               boolean,
    category_id        bigint                                  not null,
    initiator_id       bigint                                  not null,
    location_lat       double precision                        not null,
    location_lon       double precision                        not null,
    created_on         timestamp without time zone             not null,
    description        varchar(7000)                           not null,
    participant_limit  int,
    published_on       timestamp without time zone,
    request_moderation boolean,
    state              varchar(255),
    constraint pk_events primary key (id),
    constraint fk_events_categories foreign key (category_id) references categories (id) on delete cascade,
    constraint fk_events_users foreign key (initiator_id) references users (id) on delete cascade
);

create table if not exists comments
(
    id         bigint generated by default as identity not null,
    author_id  bigint                                  not null,
    text       varchar(7000)                           not null,
    event_id   bigint                                  not null,
    created timestamp without time zone             not null,
    edited timestamp without time zone,
    constraint pk_comments primary key (id),
    constraint fk_comments_users foreign key (author_id) references users (id) on delete cascade,
    constraint fk_comments_events foreign key (event_id) references events (id) on delete cascade
);

create table if not exists participations
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id bigint                                  not null,
    event_id     bigint                                  not null,
    status       varchar(255)                            not null,
    created      timestamp without time zone             not null,
    constraint pk_participations primary key (id),
    constraint fk_participations_users foreign key (requester_id) references users (id) on delete cascade,
    constraint fk_participations_events foreign key (event_id) references events (id) on delete cascade
);

create table if not exists compilations_events
(
    compilation_id bigint not null,
    event_id       bigint not null,
    constraint pk_compilations_events primary key (compilation_id, event_id),
    constraint fk_compilations_events_compilations foreign key (compilation_id) references compilations (id) on delete cascade,
    constraint fk_compilations_events_events foreign key (event_id) references events (id) on delete cascade
)