version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: stats-image:latest
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_DB_NAME=stats
      - STATS_USER=root
      - STATS_PASSWORD=root
      - STATS_DB_HOST=db
      - STATS_DB_PORT=5432


  stats-db:
    image: postgres:15
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stats
      PGDATA: /data/postgres
    volumes:
      - stats-db:/data/postgres

  ewm-service:
    build: ./ewm-service
    image: ewm-image:latest
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - EWM_DB_NAME=stats
      - EWM_USER=root
      - EWM_PASSWORD=root
      - EWM_DB_HOST=db
      - EWM_DB_PORT=5432

  ewm-db:
    image: postgres:15
    container_name: ewm-db
    ports:
      - "6542:5433"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ewm
      PGDATA: /data/postgres
    volumes:
      - ewm-db:/data/postgres


volumes:
  stats-db:
  ewm-db: