version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: stats-image:latest
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_DB_NAME=stats
      - STATS_USER=root
      - STATS_PASSWORD=root
      - STATS_DB_HOST=db
      - STATS_DB_PORT=5432


  stats-db:
    image: postgres:15
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stats
      PGDATA: /data/postgres
    volumes:
      - stats-db:/data/postgres

  ewm-service:
    build: ./ewm-service
    image: ewm-image:latest
    container_name: ewm-service
    ports:
      - "8080:8080"
#    depends_on:
#      - ewm-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/ewm
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root

#  ewm-db:
#    image: postgres:15


volumes:
  stats-db:
#  ewm-db: